### ISSUE TITLE
Discount creation & update sad path enhancements

### ISSUE THREAD

**Issue by rrabinovitch** [rrabinovitch/m2_monster_shop_final#6]
- [ ] Incomplete form repopulates with incomplete info (maybe addressed by getting `render :new` to work?)

- [ ] Have flash message specify which fields are missing

- [ ] Needed to use `redirect_to` in order for sad path to work when discount creation form unsuccessfully submitted. How can I make `render :new` work?

```
Failures:

  1) As a merchant employee If I try to create a discount without filling out all the required fields, I see a flash message prompting me to re-fill the form.
     Failure/Error: <%= form_for([:merchant, @discount]) do |f| %>
     
     ActionView::Template::Error:
       First argument in form cannot contain nil or be empty
     # ./app/views/merchant/discounts/new.html.erb:4:in `_app_views_merchant_discounts_new_html_erb___710263612622542620_70335386659540'
     # ./app/controllers/merchant/discounts_controller.rb:20:in `create'
     # ./spec/features/merchants/discounts/new_spec.rb:32:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   First argument in form cannot contain nil or be empty
     #   ./app/views/merchant/discounts/new.html.erb:4:in `_app_views_merchant_discounts_new_html_erb___710263612622542620_70335386659540'
```

**Comment by rrabinovitch** [comment]
try prying into view to see what resources I have access to
